// jsPDF handout generator — lazy-loaded by the assessment controller.
// Entry point: buildHandoutPDF.

import { jsPDF } from "jspdf";
import { APP_VERSION } from "../lib/version";
import { BRAND } from "../lib/brand";

export type HandoutSummary = {
  profile?: string;
  title: string;
  sub?: string;
  bullets: string[];
  paragraphs: string[];
  docs: [string, string][];
  trail: {
    q: string;
    a: string;
    /** Optional per-product picks captured when the user answered an umbrella
     *  question in interactive breakdown mode. Absent for show-all mode. */
    subAnswers?: { name: string; answer: "yes" | "no" }[];
  }[];
};

const COLORS = {
  blue: BRAND.blue,
  navy: BRAND.navy,
  text: "#222222",
  muted: "#666666",
  rule: "#cccccc",
  warn: "#f7630c",
  warnBg: "#fff4ce",
  square: BRAND.squares,
} as const;

const MARGIN_X = 18;
const MARGIN_TOP = 18;
const MARGIN_BOTTOM = 22;

type Doc = jsPDF;

export async function buildHandoutPDF(s: HandoutSummary): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const contentW = pageW - MARGIN_X * 2;

  let y = MARGIN_TOP;

  const ensureSpace = (need: number) => {
    if (y + need > pageH - MARGIN_BOTTOM) {
      addFooter(doc, pageW, pageH);
      doc.addPage();
      y = MARGIN_TOP;
      addHeader(doc, pageW);
      y += 14;
    }
  };

  const heading = (label: string, size = 14, color = COLORS.navy) => {
    ensureSpace(12);
    doc.setFont("helvetica", "bold").setFontSize(size).setTextColor(color);
    doc.text(label, MARGIN_X, y);
    y += size * 0.4 + 1;
    doc.setDrawColor(COLORS.blue).setLineWidth(0.3);
    doc.line(MARGIN_X, y, pageW - MARGIN_X, y);
    y += 4;
    doc.setTextColor(COLORS.text);
  };

  const paragraph = (
    text: string,
    opts: { size?: number; bold?: boolean; color?: string; indent?: number } = {}
  ) => {
    const size = opts.size ?? 10;
    const indent = opts.indent ?? 0;
    doc
      .setFont("helvetica", opts.bold ? "bold" : "normal")
      .setFontSize(size)
      .setTextColor(opts.color ?? COLORS.text);
    const lines = doc.splitTextToSize(text, contentW - indent) as string[];
    for (const line of lines) {
      ensureSpace(size * 0.5);
      doc.text(line, MARGIN_X + indent, y);
      y += size * 0.42;
    }
    y += 1;
  };

  const bullet = (text: string) => {
    const size = 10;
    doc.setFont("helvetica", "normal").setFontSize(size).setTextColor(COLORS.text);
    const lines = doc.splitTextToSize(text, contentW - 6) as string[];
    lines.forEach((line, i) => {
      ensureSpace(size * 0.5);
      doc.text(i === 0 ? "•" : " ", MARGIN_X, y);
      doc.text(line, MARGIN_X + 4, y);
      y += size * 0.42;
    });
    y += 1;
  };

  const callout = (text: string, color = COLORS.warn, bg = COLORS.warnBg) => {
    const size = 9.5;
    doc.setFont("helvetica", "normal").setFontSize(size);
    const lines = doc.splitTextToSize(text, contentW - 8) as string[];
    const height = lines.length * size * 0.45 + 6;
    ensureSpace(height + 2);
    doc.setFillColor(bg).rect(MARGIN_X, y - size * 0.35, contentW, height, "F");
    doc.setFillColor(color).rect(MARGIN_X, y - size * 0.35, 1.2, height, "F");
    doc.setTextColor(COLORS.text);
    let ty = y + 1.5;
    for (const line of lines) {
      doc.text(line, MARGIN_X + 4, ty);
      ty += size * 0.45;
    }
    y += height + 3;
  };

  // ---------- Cover ----------
  addHeader(doc, pageW);
  y = MARGIN_TOP + 14;
  doc.setFont("helvetica", "bold").setFontSize(20).setTextColor(COLORS.blue);
  doc.text("M365 Licensing Recommendation", MARGIN_X, y);
  y += 7;
  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(COLORS.muted);
  doc.text(
    `Generated ${new Date().toLocaleDateString()} · ${BRAND.name} ${APP_VERSION}`,
    MARGIN_X,
    y
  );
  y += 8;

  callout(
    "Unofficial. This handout is generated by an independent community helper and is not Microsoft guidance. Verify SKUs and entitlements with your Microsoft account team. Microsoft Product Terms are the source of truth."
  );

  heading("Context");
  if (s.profile) paragraph(`Profile: ${s.profile}`, { bold: true });
  if (!s.profile) paragraph("(no profile recorded)", { color: COLORS.muted });

  heading("Recommendation");
  paragraph(s.title, { size: 13, bold: true, color: COLORS.navy });
  if (s.sub) paragraph(s.sub, { color: COLORS.muted });
  s.paragraphs.forEach((p) => paragraph(p));
  if (s.bullets.length) {
    y += 1;
    s.bullets.forEach(bullet);
  }

  if (s.trail.length) {
    heading("Your answers");
    s.trail.forEach((t, i) => {
      paragraph(`${i + 1}. ${t.q}`, { bold: true, size: 9.5 });
      paragraph(`→ ${t.a || "(no selection)"}`, { color: COLORS.muted, size: 9.5, indent: 4 });
      if (t.subAnswers?.length) {
        t.subAnswers.forEach((sa) => {
          paragraph(`• ${sa.name}: ${sa.answer === "yes" ? "Yes" : "No"}`, {
            color: COLORS.muted,
            size: 9,
            indent: 8,
          });
        });
      }
    });
  }

  if (s.docs.length) {
    heading("Sources & further reading");
    doc.setFontSize(9.5);
    s.docs.forEach(([label, url], i) => {
      ensureSpace(8);
      doc.setFont("helvetica", "bold").setTextColor(COLORS.text);
      (doc.splitTextToSize(`${i + 1}. ${label}`, contentW) as string[]).forEach((line) => {
        doc.text(line, MARGIN_X, y);
        y += 4;
      });
      doc.setFont("helvetica", "normal").setTextColor(COLORS.blue);
      (doc.splitTextToSize(url, contentW - 4) as string[]).forEach((line) => {
        doc.textWithLink(line, MARGIN_X + 4, y, { url });
        y += 4;
      });
      y += 1;
    });

    // Universal authoritative-source footnote. Microsoft Learn references
    // describe how to operate features; the Product Terms govern licensing.
    y += 2;
    paragraph(
      "Authoritative source — the legally binding Use Rights for every Microsoft Online Service named above live in the Microsoft Product Terms (https://www.microsoft.com/licensing/terms), with per-SKU entries under Product Offerings (https://www.microsoft.com/licensing/terms/productoffering) and cross-cutting rules in the Universal License Terms and the 'For Online Services' section. Program-level changes are published on the Microsoft Licensing Hub (https://www.microsoft.com/en-us/licensing) — notably the Microsoft 365 + Teams 2025 packaging update and the 2024 External Users definition. Verify SKU eligibility with your Microsoft account team before purchase.",
      { size: 8.5, color: COLORS.muted }
    );
  }

  addFooter(doc, pageW, pageH);
  doc.save(buildFilename(s));
}

function addHeader(doc: Doc, pageW: number): void {
  const x = MARGIN_X;
  const y = 10;
  const sq = 3;
  COLORS.square.forEach((color, i) => {
    doc.setFillColor(color);
    doc.rect(x + (i % 2) * (sq + 0.6), y + Math.floor(i / 2) * (sq + 0.6), sq, sq, "F");
  });
  doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(COLORS.blue);
  doc.text(BRAND.name, x + 10, y + 4.5);
  doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(COLORS.muted);
  doc.text(`${BRAND.tagline} · Unofficial`, x + 10, y + 8);
  doc.setDrawColor(COLORS.blue).setLineWidth(0.6);
  doc.line(x, y + 12, pageW - x, y + 12);
}

function addFooter(doc: Doc, pageW: number, pageH: number): void {
  const y = pageH - 10;
  doc.setDrawColor(COLORS.rule).setLineWidth(0.2);
  doc.line(MARGIN_X, y - 4, pageW - MARGIN_X, y - 4);
  doc.setFontSize(8).setTextColor(COLORS.muted).setFont("helvetica", "normal");
  doc.text(
    `${BRAND.name} ${APP_VERSION} — unofficial. Verify with Microsoft Product Terms.`,
    MARGIN_X,
    y
  );
  doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageW - MARGIN_X, y, { align: "right" });
}

function buildFilename(s: HandoutSummary): string {
  const slug = (s.title || "recommendation")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `m365-profile-${slug}-${new Date().toISOString().slice(0, 10)}.pdf`;
}
